[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://nounouproject-production.up.railway.app/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "https://nounouproject.netlify.app"
    Access-Control-Allow-Credentials = "true"
